eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    healthcheck:
      enabled: true

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      auto-index-creation: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO