server:
  port: 8761

eureka:
  instance:
    hostname: discovery-server
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: discovery-service