server:
  port: 8084

spring:
  application:
    name: customer-service
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: customerdb
      auto-index-creation: true

customer:
  validation:
    document-number:
      pattern: "^[0-9]{8,15}$"
  business-rules:
    personal:
      max-accounts: 1
    business:
      allowed-account-types: CHECKING

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics